### ISSUE TITLE
No new version on Puppet Forge since 2019

### ISSUE THREAD

**Issue by lionelwidmer** [voxpupuli/puppet-alternatives#117]
Hi,
There is no new versin since 03.03.2019 (v3.0.0)
Would it be possible to publish a new version on Puppet Forge ?
I am particularely interested by the fact this modules now officially supports Puppet 7
Cheers

**Comment by alexjfisher** [comment]
4.2.0 was [released](https://forge.puppet.com/modules/puppet/alternatives/4.2.0) today.
