### ISSUE TITLE
Adding new alternative_entry fails

### ISSUE THREAD

**Issue by applewiskey** [voxpupuli/puppet-alternatives#18]
You can't have more than one alternative_entry or create new alternative_entry if one was added manually as provider tries to remove this alternative.

Example:
```puppete
  alternative_entry { '/etc/hadoop/conf.one:
    ensure   => present,
    altlink  => '/etc/hadoop/conf',
    altname  => 'hadoop-conf',
    priority => 99,
  }
```
Will work only if no /var/lib/alternatives/hadoop-conf

And eve we have no such entry if we try to add one more alternative entry:
```puppet
  alternative_entry { '/etc/hadoop/conf.empty':
    ensure   => present,
    altlink  => '/etc/hadoop/conf',
    altname  => 'hadoop-conf',
    priority => 10,
  }
Notice: /Stage[main]/Wg::Dwh::Jenkins/Alternative_entry[/etc/hadoop/conf.one]/altlink: defined 'altlink' as '/etc/hadoop/conf'
Notice: /Stage[main]/Wg::Dwh::Jenkins/Alternative_entry[/etc/hadoop/conf.one]/altname: defined 'altname' as 'hadoop-conf'
Notice: /Stage[main]/Wg::Dwh::Jenkins/Alternative_entry[/etc/hadoop/conf.one]/priority: defined 'priority' as '99'
Error: Execution of '/usr/sbin/alternatives --remove hadoop-conf /etc/hadoop/conf.empty' returned 2: /etc/hadoop/conf.empty has not been configured as an alternative for hadoop-conf
Error: /Stage[main]//Alternative_entry[/etc/hadoop/conf.empty]/altlink: change from absent to /etc/hadoop/conf failed: Execution of '/usr/sbin/alternatives --remove hadoop-conf /etc/hadoop/conf.empty' returned 2: /etc/hadoop/conf.empty has not been configured as an alternative for hadoop-conf
```

**Comment by valtri** [comment]
I had the same issue (only with rpm, dpkg works fine) and this patch helps.

**Comment by tuxmea** [comment]
I can confirm that adding an entry works on debian but not on RedHat family systems.

**Comment by joshsouza** [comment]
Would it be possible to get the newest code published on the Puppetforge? This change is working great, and it's a shame to not have any updates to the Forge entry since December 2014. I don't have a problem sourcing from GitHub, but I'm sure it'll trip up a few folks who are using the Forge directly.

**Comment by bastelfreak** [comment]
Hi @joshsouza, I'm currently working on a modulesync in https://github.com/voxpupuli/puppet-alternatives/pull/31 and will do a new release after travis is green there.
