### ISSUE TITLE
How does one set alternative entry back to 'auto' mode?

### ISSUE THREAD

**Issue by felipe1982** [voxpupuli/puppet-alternatives#32]
When I first set up the alternative_entry, mode is set to 'auto' by default. Any subsequent change of the path forced mode to be manual. only deleting and recreating the entry (`absent` && `present`) makes it auto again.

Is there a better way?

**Comment by igalic** [comment]
imo, there should be an `ensure => auto`

**Comment by jyaworski** [comment]
Looking in the file type, it appears as if we can handle alternative 'ensure' values in the type itself.

https://github.com/puppetlabs/puppet/blob/master/lib/puppet/type/file.rb

Overriding 'present' to be some sane default may be useful as well. The type module inspects $name to see if it's a file or a directory.
