### ISSUE TITLE
Release to forge

### ISSUE THREAD

**Issue by mkrakowitzer** [voxpupuli/puppet-alternatives#36]
Would it be possible to publish this module the the forge under the puppet namespace please?

The last release seems to be to: https://forge.puppet.com/adrien/alternatives in 2014. 

Thanks

**Comment by bastelfreak** [comment]
We released 1.0.1 which is now available on the forge. https://forge.puppet.com/puppet/alternatives

**Comment by mkrakowitzer** [comment]
ty
