### ISSUE TITLE
Debian 6 with Ruby 1.8.7 broken

### ISSUE THREAD

**Issue by lazyfrosch** [voxpupuli/puppet-alternatives#42]
Just switches over from saz' module version, and it seems like there is a new Rubyism that is not supported on 1.8.7.

Fix or de-support Debian 6?
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 3.8.2
- Ruby: 1.8.7 (2010-08-16 patchlevel 302)
- Distribution: Debian GNU/Linux 6.0.10 (squeeze)
- Module version: 1.0.1
### How to reproduce (e.g Puppet code you use)

While loading types on the system.
### What are you seeing

```
$ puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Loading facts
Error: Could not autoload puppet/type/alternatives: /var/lib/puppet/lib/puppet/type/alternatives.rb:4: syntax error, unexpected ':', expecting ')'
  newparam(:name, isnamevar: true) do
                            ^
/var/lib/puppet/lib/puppet/type/alternatives.rb:16: syntax error, unexpected ':', expecting ')'
  newproperty(:mode, required_features: [:mode]) do
                                       ^
/var/lib/puppet/lib/puppet/type/alternatives.rb:16: syntax error, unexpected ')', expecting $end
  newproperty(:mode, required_features: [:mode]) do
                                                ^
Error: Could not retrieve catalog from remote server: Could not intern from text/pson: Could not autoload puppet/type/alternatives: /var/lib/puppet/lib/puppet/type/alternatives.rb:4: syntax error, unexpected ':', expecting ')'
  newparam(:name, isnamevar: true) do
                            ^
/var/lib/puppet/lib/puppet/type/alternatives.rb:16: syntax error, unexpected ':', expecting ')'
  newproperty(:mode, required_features: [:mode]) do
                                       ^
/var/lib/puppet/lib/puppet/type/alternatives.rb:16: syntax error, unexpected ')', expecting $end
  newproperty(:mode, required_features: [:mode]) do
                                                ^
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by juniorsysadmin** [comment]
@lazyfrosch Release 1.01 dropped Ruby 1.8.7 support and if any module in the Vox Pupuli namespace currently works with Ruby 1.8.7, it's not deliberately. My recommendation would be to jump to Puppet 4 which bundles Ruby 2.1 or alternatively use rvm/rbenv to run Puppet 3 under a newer Ruby version. Note that Puppet 3 is going EOL at the end of the year, but we intend to drop Puppet 3 support in Vox Pupuli modules later next year. See https://github.com/voxpupuli/plumbing/issues/21

**Comment by lazyfrosch** [comment]
@juniorsysadmin I'm going rid of that box either way, just wanted to raise awareness, since you support 3.x and Debian 6 :wink:

**Comment by bastelfreak** [comment]
sadly the metadata.json doesn't support a detailed matrix. Puppet3 works, for example on Debian 8. Puppet 4 works with this module on Debian 6, just not Debian/CentOS 6 with Puppet3 because of the outdated platform itself and Ruby version.
