### ISSUE TITLE
missing alternatives is not added - it breaks instead

### ISSUE THREAD

**Issue by KlavsKlavsen** [voxpupuli/puppet-alternatives#54]
This:
alternatives { 'java': path => "/usr/java/jre1.8.0-101/bin/java" }
Gives me:
 Could not evaluate: Execution of '/sbin/alternatives --display java' returned 2: failed to read link /usr/bin/java: No such file or directory

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.2
- Ruby: 2.0.0
- Distribution: CentOS 7
- Module version: Git HEAD as of today

**Comment by westbywest** [comment]
Confirming am also affected by this problem.

- Puppet: 4.6.2
- Distribution: CentOS 7.3.11
- Module version: v1.1.0

I have to call alternatives directly via exec, e.g.:
`exec { 'install keytool alternatives':
  command => "/usr/sbin/alternatives --install /usr/bin/keytool keytool ${::java_default_home}/jre/bin/keytool 20000",
  unless => "/usr/sbin/alternatives --list | grep keytool",
}`

**Comment by westbywest** [comment]
Further detail on this problem is that the first invocation of any alternative_entry{} resource triggers "Prefetching rpm resources for alternative_entry," whereby the module runs "/usr/sbin/alternatives --display ..." on all defined entries.  Return value >0 on any of these instances apparently causes the entire catalog to fail.  This seems unreasonably fragile.

**Comment by westbywest** [comment]
My recurring problem is openjdk rpm under RHEL/CentOS sometimes leaves a broken alternatives entry for keytool.  My resolution is have an exec remove the broken alternatives entry prior to any alternative_entry{} resource gets declared, which is awkward.
```
include java

# Remove broken alternatives entry before *any* alternative_entry{} resource
exec {
  'remove broken keytool alternatives entry':
    command => "rm -rf /var/lib/alternatives/keytool",
    path    => ['/usr/bin', '/usr/sbin', '/bin'],
    onlyif => "egrep '^/usr/bin/keytool' /var/lib/alternatives/keytool",
    unless => 'test -f /usr/bin/keytool';
}
Exec['remove broken keytool alternatives entry'] -> Alternative_Entry<| |>

# Now let puppet/alternatives add the keytools entry
alternative_entry { "${::java_default_home}/jre/bin/keytool":
  ensure   => present,
  altlink  => '/usr/bin/keytool',
  altname  => 'keytool',
  priority => 20000, # This is priority set by puppetlabs/java
  require  => Class['java'],
}
```
