### ISSUE TITLE
Using a full path for path is not always desirable.

### ISSUE THREAD

**Issue by traylenator** [voxpupuli/puppet-alternatives#71]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.9
- Ruby:
- Distribution: CentOS 7
- Module version: 0.3.0

Old version of module I know but looks to to be the same in 2.0.0

## How to reproduce (e.g Puppet code you use)

```puppet
alternatives{'java':
    path => 'java-1.8.0-openjdk',
}
```

## What are you seeing
Rejected because `java-1.8.0-openjdk` is not fully qualified path

## What behaviour did you expect instead
Should wiork.

Particualarly on CentOS 7

````
# alternatives --config java

There is 4 program that provides 'java'.


  Selection    Command
-----------------------------------------------
   1           java-1.7.0-openjdk.x86_64 (/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.161-2.6.12.0.el7_4.x86_64/jre/bin/java)
*+ 2           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/bin/java)
   3           /usr/lib/jvm/jre-1.8.0-oracle.x86_64/bin/java
   4           /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java

````

while using 

```puppet
alternatives{'java':
    path => '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/bin/java',
}
```

does work it is a pain since as the package is updated to the new version this hard coded
version must be updated.

The following command does work.

```bash
alternatives  --set java java-1.8.0-openjdk.x86_64
```
does work but this is currently not possible via the alternatives puppet type

## Any additional information you'd like to impart
Maybe a new paramater is the way to go.

**Comment by traylenator** [comment]
Workaround:
```puppet
   exec{'jdk8':
      command => '/usr/bin/alternatives  --set java java-1.8.0-openjdk.x86_64',
      unless  => '/usr/bin/readlink /etc/alternatives/java | /usr/bin/grep -q /java-1.8.0-openjdk-1.8.0'
    }
```

**Comment by tuxmaster5000** [comment]
Are there any news?

**Comment by sharumpe** [comment]
Just hit this as well. Upvote, FWIW.

**Comment by sharumpe** [comment]
Just added a PR to simply remove the validation line.  Don't know that there's a great solution to also looking at "families", but I haven't dug into the alternatives system much.  A quick look appears that the "family" thing is not a term mentioned in the man pages.  But as the OP and I have discovered, it _does_ seem to work for the JDK, at least.

**Comment by sharumpe** [comment]
...and, as with all things, it turned out not to be that simple, of course.  :D
Since my setup doesn't need to have multiple jdk's installed, I'm going to punt, but it would be great if this _could_ work.  I'll look at it more as I get time, but for now, my PR just results in puppet setting the alternative every run, which is obviously not desired.

**Comment by tkriener** [comment]
Would be great if this could be fixed.

Here is a workaround for Java 11 under RHEL 7:

```
alternative_entry {'/usr/lib/jvm/jre-11-openjdk/bin/java':
    ensure   => present,
    altlink  => '/usr/bin/java',
    altname  => 'java',
    priority => 999999,
    require  => Package['java-11-openjdk-headless'],
}

alternatives { 'java':
  path    => '/usr/lib/jvm/jre-11-openjdk/bin/java',
  require => Alternative_entry['/usr/lib/jvm/jre-11-openjdk/bin/java'],
}
```

This adds an entry with a static path using the already available link under /usr/lib/jvm
